name: qrcode_flutter
description: Flutter plugin for scanning QR codes.You can customize your page by using PlatformView.Scanning Picture from path (photo album).
version: 3.0.0-nullsafety.0
# author: JSShou <xuzhongpeng.name@gmail.com>
homepage: https://github.com/xuzhongpeng/qrcode_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"
  
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: any
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.xzp.qrcode_flutter
        pluginClass: QrcodeFlutterPlugin 
      ios:
        pluginClass: QrcodeFlutterPlugin
      web:
        pluginClass: QrcodeFlutterWeb
        fileName: qrcode_flutter_web.dart
  assets:
    - assets/